#!/bin/sh

. /lib/functions.sh

PID=

# Only engage on WPS, RESET or WiFi button
[ ! "$BUTTON" = wps -o "$BUTTON" = reset ] && return 0

# Don't execute when not in setup-mode
[ ! -r /tmp/gluon-setup-mode-active ] && return 0

export UCI_CONFIG_DIR=/var/gluon/setup-mode/config
config_load wireless

enable_wifi_iface() {
	uci_set wireless "$1" disabled "0"
}

disable_wifi_iface() {
	uci_set wireless "$1" disabled "1"
}

wait_disable_wifi() {
	sleep 300
	disable_wifi
}

disable_wifi() {
	config_foreach disable_wifi_iface wifi-iface
	uci_commit
	wifi
	rm /tmp/gluon-setup-mode-wifi-active
}

enable_wifi() {
	config_foreach enable_wifi_iface wifi-iface
	uci_commit
	wifi
	wait_disable_wifi &
	PID=$!
	echo $PID > /tmp/gluon-setup-mode-wifi-active
}

# Get PID in case WiFi is already active
if [ -r /tmp/gluon-setup-mode-wifi-active ]; then
	PID=$(cat /tmp/gluon-setup-mode-wifi-active)
fi

case "$ACTION" in
	pressed)
		if [[ -z "$PID" ]]; then
			enable_wifi
		else
			kill $(cat /tmp/gluon-setup-mode-wifi-active)
			disable_wifi
		fi
		;;
esac
