#!/bin/sh

. /lib/functions.sh

export UCI_CONFIG_DIR=/var/gluon/setup-mode/config
config_load wireless

enable_wifi() {
	uci_set wireless "$1" disabled "0"
}

disable_wifi() {
	uci_set wireless "$1" disabled "1"
}

# Don't execute when not in setup-mode
if [! -r /tmp/gluon-setup-mode-active ]; then
	exit 0
fi

# Don't execute in case wifi is already active
if [ -r /tmp/gluon-setup-mode-wifi-active ]; then
	exit 0
fi


if [ "$BUTTON" = wps -o "$BUTTON" = reset -o "$BUTTON" = rfkill ]; then
	case "$ACTION" in
		pressed)
			touch /tmp/gluon-setup-mode-wifi-active
			config_foreach enable_wifi wifi-iface
			uci_commit
			wifi
			sleep 600
			config_foreach disable_wifi wifi-iface
			uci_commit
			wifi
			rm /tmp/gluon-setup-mode-wifi-active
			;;
	esac
fi
