#!/bin/sh /etc/rc.common

START=35
STOP=85
USE_PROCD=1

start_service() {
	cp /lib/gluon/setup-mode/dhcp.config /var/gluon/setup-mode/config/dhcp

	procd_open_instance
	procd_set_param command /usr/sbin/odhcpd -c /var/gluon/setup-mode/config
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	procd_send_signal odhcpd
}

service_triggers()
{
	procd_add_reload_trigger "dhcp"
}

