include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-statistics

include ../gluon.mk

define Package/gluon-statistics
  TITLE:=gluon-web module for gluon-statistics
  DEPENDS:=+gluon-ucode
endef

$(eval $(call BuildPackageGluon,gluon-statistics))
