#!/usr/bin/lua

local uci = require('simple-uci').cursor()
local vpn = require('gluon.mesh-vpn.core').get_active_method()

local vpn_config = {
	enabled = uci:get_bool('gluon', 'mesh_vpn', 'enabled'),
	limit_enabled = uci:get_bool('gluon', 'mesh_vpn', 'limit_enabled'),
	limit_egress = uci:get('gluon', 'mesh_vpn', 'limit_egress'),
	limit_ingress = uci:get('gluon', 'mesh_vpn', 'limit_ingress'),
}

uci:delete('simple-tc', 'mesh_vpn')
uci:section('simple-tc', 'interface', 'mesh_vpn', {
	ifname = 'mesh-vpn',
	enabled = vpn_config.limit_enabled,
	limit_egress = vpn_config.limit_egress,
	limit_ingress = vpn_config.limit_ingress,
})

vpn.enable(vpn_config.enabled)
if vpn_config.limit_enabled then
	vpn.set_limit(vpn_config.limit_ingress, vpn_config.limit_egress)
else
	vpn.set_limit(nil, nil)
end

uci:save('simple-tc')
